# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/hello.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/hello.proto',
  package='hello',
  syntax='proto3',
  serialized_options=_b('Z\001p'),
  serialized_pb=_b('\n\x11proto/hello.proto\x12\x05hello\"*\n\nHelloInput\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06repeat\x18\x02 \x01(\x05\"$\n\x0bHelloOutput\x12\x15\n\rhello_message\x18\x01 \x01(\t27\n\x05Hello\x12.\n\x05Hello\x12\x11.hello.HelloInput\x1a\x12.hello.HelloOutputB\x03Z\x01pb\x06proto3')
)




_HELLOINPUT = _descriptor.Descriptor(
  name='HelloInput',
  full_name='hello.HelloInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='hello.HelloInput.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='repeat', full_name='hello.HelloInput.repeat', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=70,
)


_HELLOOUTPUT = _descriptor.Descriptor(
  name='HelloOutput',
  full_name='hello.HelloOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hello_message', full_name='hello.HelloOutput.hello_message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=108,
)

DESCRIPTOR.message_types_by_name['HelloInput'] = _HELLOINPUT
DESCRIPTOR.message_types_by_name['HelloOutput'] = _HELLOOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloInput = _reflection.GeneratedProtocolMessageType('HelloInput', (_message.Message,), dict(
  DESCRIPTOR = _HELLOINPUT,
  __module__ = 'proto.hello_pb2'
  # @@protoc_insertion_point(class_scope:hello.HelloInput)
  ))
_sym_db.RegisterMessage(HelloInput)

HelloOutput = _reflection.GeneratedProtocolMessageType('HelloOutput', (_message.Message,), dict(
  DESCRIPTOR = _HELLOOUTPUT,
  __module__ = 'proto.hello_pb2'
  # @@protoc_insertion_point(class_scope:hello.HelloOutput)
  ))
_sym_db.RegisterMessage(HelloOutput)


DESCRIPTOR._options = None

_HELLO = _descriptor.ServiceDescriptor(
  name='Hello',
  full_name='hello.Hello',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=110,
  serialized_end=165,
  methods=[
  _descriptor.MethodDescriptor(
    name='Hello',
    full_name='hello.Hello.Hello',
    index=0,
    containing_service=None,
    input_type=_HELLOINPUT,
    output_type=_HELLOOUTPUT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HELLO)

DESCRIPTOR.services_by_name['Hello'] = _HELLO

# @@protoc_insertion_point(module_scope)
